# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Neeraj Sharma
baseurl: '/blog'
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about the latest in tech that i stumble upon.
url: "http://neeraj.me" # the base hostname & protocol for your site
twitter_username: neeraj2972

# Build settings
markdown: kramdown
permalink: /:title
